name: horusec-security
on:
  push:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Update Git
      run: |
        sudo add-apt-repository ppa:git-core/ppa
        sudo apt-get update
        sudo apt-get install -y git

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Horusec CLI
      run: |
        curl -fsSL https://github.com/ZupIT/horusec/releases/download/v2.8.0/horusec_linux_amd64 -o horusec
        chmod +x horusec
        sudo mv horusec /usr/local/bin/

    - name: Running Horusec Security without Docker
      run: horusec start -p . --disable-docker --output-format=json --json-output-file=./horusec-output.json

    - name: Display Horusec Output
      run: cat ./horusec-output.json
